### ISSUE TITLE
build problems

### ISSUE THREAD

**Issue by jonleivent** [gmalecha/coq-ltac-iter#3]
I just tried building the latest version, and got this:

[make-out.txt](https://github.com/gmalecha/coq-ltac-iter/files/111585/make-out.txt)

**Comment by gmalecha** [comment]
This package now depends on PluginUtils (previously I had just copy-pasted some of that code into this repo). Once the opam pull request is merged, you should be able to install it via `opam install coq-ltac-iter`. I will update the documentation.

**Comment by gmalecha** [comment]
README.md updated in a54388401c39eefcdb39aa7c0a1d5165a2c00968
