### ISSUE TITLE
Typo in README.md: leftover "run" keyword

### ISSUE THREAD

**Issue by jeremie-koenig** [gmalecha/coq-ltac-iter#4]
Hi Gregory,

The example in README.md still has `foreach [ db:my_lemmas ] run k`; you may want to drop `run`.

Best,

**Comment by jeremie-koenig** [comment]
Also, "combines the invocations of k in the same **was a** first" -> should read **way as**.

**Comment by gmalecha** [comment]
Fixed in d418ff867e8cd0524f17f40f0c94860dc0611984.

In the future, feel free to submit pull-requests.
